### ISSUE TITLE
Failing to add sudo privileges to user

### ISSUE THREAD

**Issue by bostone** [GROG/ansible-role-sudo#4]
I'm trying your basic example on SLES 11. The goal is to add sudo privileges to the existing "pdo" user

```
- hosts: clients
  roles:
  - { role: GROG.sudo, become: yes }
```

hosts file

```
[clients]
as0061
as0063
[db]
as0064
```

clients.yml

```
sudo_list_group:
  - name: pdo
    sudo:
      hosts: ALL
      as: ALL
      commands: ALL
      nopasswd: yes
```

When I run it with 
ansible-playbook ./sudo-client.yml -K
I get this error

```
TASK [GROG.sudo : Make sure sudoers.d dir is available] ************************
fatal: [as0061]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", 
"module_stdout": "\r\nSorry, try again.\r\n[sudo via ansible, 
key=pwstxgartlkdfysrplianfqijriswxqq] password: \r\nsudo: 1 incorrect password attempt\r\n", 
"msg": "MODULE FAILURE", "parsed": false}
```

The directory is there, BTW. Can you please let me know what am I doing wrong?

Thanks,
Bo Stone
